### ISSUE TITLE
Should just accept mode int

### ISSUE THREAD

**Issue by CMCDragonkai** [TooTallNate/stat-mode#7]
I have encountered a situation where the stat object doesn't exist, but the mode int is available, this library's functions should work on just the mode int right? Can we add a way to make it just take a mode int and work with it?

**Comment by CMCDragonkai** [comment]
DW found a way around it:

```
var mode = new Mode({ mode: stat.mode });
```

**Comment by TooTallNate** [comment]
Ya I've done that in the past. Patch welcome to add that example to the Readme!
